In [43]:
from orion.data import load_signal
from orion import Orion

train_data = load_signal('S-1-train')
train_data.head()

    timestamp     value
0  1222819200 -0.366359
1  1222840800 -0.394108
2  1222862400  0.403625
3  1222884000 -0.362759
4  1222905600 -0.370746

In [55]:
from orion import Orion

hyperparameters = {
    'keras.Sequential.LSTMTimeSeriesRegressor#1': {
        'epochs': 5,
        'verbose': True
    }
}

orion = Orion(
    pipeline='lstm_dynamic_threshold',
    hyperparameters=hyperparameters
)

orion.fit(train_data)

Using TensorFlow backend.

WARNING:tensorflow:From /Users/jacobrodriguez/Applications/anaconda3/envs/Project_258/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From /Users/jacobrodriguez/Applications/anaconda3/envs/Project_258/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

Train on 2054 samples, validate on 514 samples
Epoch 1/5
2054/2054 [==============================] - 11s 5ms/step - loss: 0.4753 - mse: 0.4753 - val_loss: 0.4405 - val_mse: 0.4405
Epoch 2/5
2054/2054 [==============================] - 12s 6ms/step - loss: 0.4248 - mse: 0.4248 - val_loss: 0.4341 - val_mse: 0.4341
Epoch 3/5
2054/2054 [==============================] - 13s 6ms/step - loss: 0.4187 - mse: 0.4187 - val_loss: 0.4301 - val_mse: 0.4301
Epoch 4/5
2054/2054 [==============================] - 15s 7ms/step - loss: 0.4099 - mse: 0.4099 - val_loss: 0.4231 - val_mse: 0.4231
Epoch 5/5
2054/2054 [==============================] - 16s 8ms/step - loss: 0.4047 - mse: 0.4047 - val_loss: 0.4218 - val_mse: 0.4218
2568/2568 [==============================] - 6s 3ms/step

In [44]:
new_data = load_signal('S-1-new')
anomalies = orion.detect(new_data)

In [4]:
anomalies

        start         end  severity
0  1398427200  1400198400  0.606089

In [45]:
new_data.head()

    timestamp     value
0  1283688000  0.028893
1  1283709600  0.403040
2  1283731200 -0.366585
3  1283752800 -0.369710
4  1283774400 -0.386455

In [13]:
import pandas as pd
dataset = pd.read_csv('./CMPE-258-Anomaly-Detection/data/AirQualityUCI.csv', delimiter=";")

In [14]:
dataset.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,10/03/2004,18.00.00,"2,6",1360.0,150.0,"11,9",1046.0,166.0,1056.0,113.0,1692.0,1268.0,"13,6","48,9","0,7578",NaN,NaN
1,10/03/2004,19.00.00,2,1292.0,112.0,"9,4",955.0,103.0,1174.0,92.0,1559.0,972.0,"13,3","47,7","0,7255",NaN,NaN
2,10/03/2004,20.00.00,"2,2",1402.0,88.0,"9,0",939.0,131.0,1140.0,114.0,1555.0,1074.0,"11,9","54,0","0,7502",NaN,NaN
3,10/03/2004,21.00.00,"2,2",1376.0,80.0,"9,2",948.0,172.0,1092.0,122.0,1584.0,1203.0,"11,0","60,0","0,7867",NaN,NaN
4,10/03/2004,22.00.00,"1,6",1272.0,51.0,"6,5",836.0,131.0,1205.0,116.0,1490.0,1110.0,"11,2","59,6","0,7888",NaN,NaN

In [15]:
dataset['Date_combined'] = pd.to_datetime(dataset['Date'] + 'T'+ dataset['Time'], format=('%d/%m/%YT%H.%M.%S'))
#dataset['Datetime'] = pd.to_datetime(dataset['Date_new'].dt.strftime('%d/%m/%Y') + 'T' + dataset['Time'])

In [36]:
import datetime
from datetime import timezone
dataset['Epoch'] = (dataset['Date_combined'] - pd.Timestamp("1970-01-01")) // pd.Timedelta('1s')

In [52]:
import numpy as np
dataset = dataset.fillna(0)
dataset['Epoch'].astype(np.int64)

0       1078941600
1       1078945200
2       1078948800
3       1078952400
4       1078956000
5       1078959600
6       1078963200
7       1078966800
8       1078970400
9       1078974000
10      1078977600
11      1078981200
12      1078984800
13      1078988400
14      1078992000
15      1078995600
16      1078999200
17      1079002800
18      1079006400
19      1079010000
20      1079013600
21      1079017200
22      1079020800
23      1079024400
24      1079028000
25      1079031600
26      1079035200
27      1079038800
28      1079042400
29      1079046000
           ...
9441             0
9442             0
9443             0
9444             0
9445             0
9446             0
9447             0
9448             0
9449             0
9450             0
9451             0
9452             0
9453             0
9454             0
9455             0
9456             0
9457             0
9458             0
9459             0
9460             0
9461             0
9462             0
9463             0
9464             0
9465             0
9466             0
9467             0
9468             0
9469             0
9470             0
Name: Epoch, Length: 9471, dtype: int64

In [53]:
dataset['timestamp'] = dataset['Epoch'].astype(np.int64)

In [54]:
dataset

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16,Date_combined,Epoch,timestamp
0,10/03/2004,18.00.00,"2,6",1360.0,150.0,"11,9",1046.0,166.0,1056.0,113.0,1692.0,1268.0,"13,6","48,9","0,7578",0.0,0.0,2004-03-10 18:00:00,1.078942e+09,1078941600
1,10/03/2004,19.00.00,2,1292.0,112.0,"9,4",955.0,103.0,1174.0,92.0,1559.0,972.0,"13,3","47,7","0,7255",0.0,0.0,2004-03-10 19:00:00,1.078945e+09,1078945200
2,10/03/2004,20.00.00,"2,2",1402.0,88.0,"9,0",939.0,131.0,1140.0,114.0,1555.0,1074.0,"11,9","54,0","0,7502",0.0,0.0,2004-03-10 20:00:00,1.078949e+09,1078948800
3,10/03/2004,21.00.00,"2,2",1376.0,80.0,"9,2",948.0,172.0,1092.0,122.0,1584.0,1203.0,"11,0","60,0","0,7867",0.0,0.0,2004-03-10 21:00:00,1.078952e+09,1078952400
4,10/03/2004,22.00.00,"1,6",1272.0,51.0,"6,5",836.0,131.0,1205.0,116.0,1490.0,1110.0,"11,2","59,6","0,7888",0.0,0.0,2004-03-10 22:00:00,1.078956e+09,1078956000
5,10/03/2004,23.00.00,"1,2",1197.0,38.0,"4,7",750.0,89.0,1337.0,96.0,1393.0,949.0,"11,2","59,2","0,7848",0.0,0.0,2004-03-10 23:00:00,1.078960e+09,1078959600
6,11/03/2004,00.00.00,"1,2",1185.0,31.0,"3,6",690.0,62.0,1462.0,77.0,1333.0,733.0,"11,3","56,8","0,7603",0.0,0.0,2004-03-11 00:00:00,1.078963e+09,1078963200
7,11/03/2004,01.00.00,1,1136.0,31.0,"3,3",672.0,62.0,1453.0,76.0,1333.0,730.0,"10,7","60,0","0,7702",0.0,0.0,2004-03-11 01:00:00,1.078967e+09,1078966800
8,11/03/2004,02.00.00,"0,9",1094.0,24.0,"2,3",609.0,45.0,1579.0,60.0,1276.0,620.0,"10,7","59,7","0,7648",0.0,0.0,2004-03-11 02:00:00,1.078970e+09,1078970400
9,11/03/2004,03.00.00,"0,6",1010.0,19.0,"1,7",561.0,-200.0,1705.0,-200.0,1235.0,501.0,"10,3","60,2","0,7517",0.0,0.0,2004-03-11 03:00:00,1.078974e+09,1078974000
10,11/03/2004,04.00.00,-200,1011.0,14.0,"1,3",527.0,21.0,1818.0,34.0,1197.0,445.0,"10,1","60,5","0,7465",0.0,0.0,2004-03-11 04:00:00,1.078978e+09,1078977600
11,11/03/2004,05.00.00,"0,7",1066.0,8.0,"1,1",512.0,16.0,1918.0,28.0,1182.0,422.0,"11,0","56,2","0,7366",0.0,0.0,2004-03-11 05:00:00,1.078981e+09,1078981200
12,11/03/2004,06.00.00,"0,7",1052.0,16.0,"1,6",553.0,34.0,1738.0,48.0,1221.0,472.0,"10,5","58,1","0,7353",0.0,0.0,2004-03-11 06:00:00,1.078985e+09,1078984800
13,11/03/2004,07.00.00,"1,1",1144.0,29.0,"3,2",667.0,98.0,1490.0,82.0,1339.0,730.0,"10,2","59,6","0,7417",0.0,0.0,2004-03-11 07:00:00,1.078988e+09,1078988400
14,11/03/2004,08.00.00,2,1333.0,64.0,"8,0",900.0,174.0,1136.0,112.0,1517.0,1102.0,"10,8","57,4","0,7408",0.0,0.0,2004-03-11 08:00:00,1.078992e+09,1078992000
15,11/03/2004,09.00.00,"2,2",1351.0,87.0,"9,5",960.0,129.0,1079.0,101.0,1583.0,1028.0,"10,5","60,6","0,7691",0.0,0.0,2004-03-11 09:00:00,1.078996e+09,1078995600
16,11/03/2004,10.00.00,"1,7",1233.0,77.0,"6,3",827.0,112.0,1218.0,98.0,1446.0,860.0,"10,8","58,4","0,7552",0.0,0.0,2004-03-11 10:00:00,1.078999e+09,1078999200
17,11/03/2004,11.00.00,"1,5",1179.0,43.0,"5,0",762.0,95.0,1328.0,92.0,1362.0,671.0,"10,5","57,9","0,7352",0.0,0.0,2004-03-11 11:00:00,1.079003e+09,1079002800
18,11/03/2004,12.00.00,"1,6",1236.0,61.0,"5,2",774.0,104.0,1301.0,95.0,1401.0,664.0,"9,5","66,8","0,7951",0.0,0.0,2004-03-11 12:00:00,1.079006e+09,1079006400
19,11/03/2004,13.00.00,"1,9",1286.0,63.0,"7,3",869.0,146.0,1162.0,112.0,1537.0,799.0,"8,3","76,4","0,8393",0.0,0.0,2004-03-11 13:00:00,1.079010e+09,1079010000
20,11/03/2004,14.00.00,"2,9",1371.0,164.0,"11,5",1034.0,207.0,983.0,128.0,1730.0,1037.0,"8,0","81,1","0,8736",0.0,0.0,2004-03-11 14:00:00,1.079014e+09,1079013600
21,11/03/2004,15.00.00,"2,2",1310.0,79.0,"8,8",933.0,184.0,1082.0,126.0,1647.0,946.0,"8,3","79,8","0,8778",0.0,0.0,2004-03-11 15:00:00,1.079017e+09,1079017200
22,11/03/2004,16.00.00,"2,2",1292.0,95.0,"8,3",912.0,193.0,1103.0,131.0,1591.0,957.0,"9,7","71,2","0,8569",0.0,0.0,2004-03-11 16:00:00,1.079021e+09,1079020800
23,11/03/2004,17.00.00,"2,9",1383.0,150.0,"11,2",1020.0,243.0,1008.0,135.0,1719.0,1104.0,"9,8","67,6","0,8185",0.0,0.0,2004-03-11 17:00:00,1.079024e+09,1079024400
24,11/03/2004,18.00.00,"4,8",1581.0,307.0,"20,8",1319.0,281.0,799.0,151.0,2083.0,1409.0,"10,3","64,2","0,8065",0.0,0.0,2004-03-11 18:00:00,1.079028e+09,1079028000
25,11/03/2004,19.00.00,"6,9",1776.0,461.0,"27,4",1488.0,383.0,702.0,172.0,2333.0,1704.0,"9,7","69,3","0,8319",0.0,0.0,2004-03-11 19:00:00,1.079032e+09,1079031600
26,11/03/2004,20.00.00,"6,1",1640.0,401.0,"24,0",1404.0,351.0,743.0,165.0,2191.0,1654.0,"9,6","67,8","0,8133",0.0,0.0,2004-03-11 20:00:00,1.079035e+09,1079035200
27,11/03/2004,21.00.00,"3,9",1313.0,197.0,"12,8",1076.0,240.0,957.0,136.0,1707.0,1285.0,"9,1","64,0","0,7419",0.0,0.0,2004-03-11 21:00:00,1.079039e+09,1079038800
28,11/03/2004,22.00.00,"1,5",965.0,61.0,"4,7",749.0,94.0,1325.0,85.0,1333.0,821.0,"8,2","63,4","0,6905",0.0,0.0,2004-03-11 22:00:00,1.079042e+09,1079042400
29,11/03/2004,23.00.00,1,913.0,26.0,"2,6",629.0,47.0,1565.0,53.0,1252.0,552.0,"8,2","60,8","0,6657",0.0,0.0,2004-03-11 23:00:00,1.079046e+09,1079046000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9441,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9442,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9443,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9444,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9445,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9446,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9447,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9448,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9449,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9450,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9451,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9452,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9453,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9454,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9455,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9456,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9457,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9458,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9459,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9460,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9461,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9462,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9463,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9464,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9465,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9466,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9467,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9468,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9469,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0
9470,0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.000000e+00,0

In [56]:
new_test = dataset[['timestamp', 'NMHC(GT)']].copy()

In [58]:
new_test = new_test.rename(columns={"NMHC(GT)":"value"})

In [60]:
new_anomals = orion.detect(new_test)

51261/51261 [==============================] - 124s 2ms/step

In [61]:
new_anomals

        start         end  severity
0  1087322400  1101729600  0.607774

## New dataset

In [69]:
dataset_aqi = pd.read_csv('./CMPE-258-Anomaly-Detection/daily_aqi_by_cbsa_2020.csv', delimiter=",")

### Convert column to datetime object

In [77]:
dataset_aqi['Date_new'] = pd.to_datetime(dataset_aqi['Date'], format=('%Y/%m/%d'))

In [78]:
dataset_aqi

,CBSA,CBSA Code,Date,AQI,Category,Defining Parameter,Defining Site,Number of Sites Reporting,Date_new,Epoch,timestamp
0,"Aberdeen, SD",10100,2020-01-01,20,Good,PM2.5,46-013-0004,1,2020-01-01,1577836800,1577836800
1,"Aberdeen, SD",10100,2020-01-02,35,Good,PM2.5,46-013-0004,1,2020-01-02,1577923200,1577923200
2,"Aberdeen, SD",10100,2020-01-03,22,Good,PM2.5,46-013-0004,1,2020-01-03,1578009600,1578009600
3,"Aberdeen, SD",10100,2020-01-04,40,Good,PM2.5,46-013-0004,1,2020-01-04,1578096000,1578096000
4,"Aberdeen, SD",10100,2020-01-05,13,Good,PM2.5,46-013-0004,1,2020-01-05,1578182400,1578182400
5,"Aberdeen, SD",10100,2020-01-06,23,Good,PM2.5,46-013-0004,1,2020-01-06,1578268800,1578268800
6,"Aberdeen, SD",10100,2020-01-07,16,Good,PM2.5,46-013-0004,1,2020-01-07,1578355200,1578355200
7,"Aberdeen, SD",10100,2020-01-08,23,Good,PM2.5,46-013-0004,1,2020-01-08,1578441600,1578441600
8,"Aberdeen, SD",10100,2020-01-09,32,Good,PM2.5,46-013-0004,1,2020-01-09,1578528000,1578528000
9,"Aberdeen, SD",10100,2020-01-10,22,Good,PM2.5,46-013-0004,1,2020-01-10,1578614400,1578614400
10,"Aberdeen, SD",10100,2020-01-11,37,Good,PM2.5,46-013-0004,1,2020-01-11,1578700800,1578700800
11,"Aberdeen, SD",10100,2020-01-12,45,Good,PM2.5,46-013-0004,1,2020-01-12,1578787200,1578787200
12,"Aberdeen, SD",10100,2020-01-13,52,Moderate,PM2.5,46-013-0004,1,2020-01-13,1578873600,1578873600
13,"Aberdeen, SD",10100,2020-01-14,35,Good,PM2.5,46-013-0004,1,2020-01-14,1578960000,1578960000
14,"Aberdeen, SD",10100,2020-01-15,30,Good,PM2.5,46-013-0004,1,2020-01-15,1579046400,1579046400
15,"Aberdeen, SD",10100,2020-01-16,60,Moderate,PM2.5,46-013-0004,1,2020-01-16,1579132800,1579132800
16,"Aberdeen, SD",10100,2020-01-17,48,Good,PM2.5,46-013-0004,1,2020-01-17,1579219200,1579219200
17,"Aberdeen, SD",10100,2020-01-18,37,Good,PM2.5,46-013-0004,1,2020-01-18,1579305600,1579305600
18,"Aberdeen, SD",10100,2020-01-19,27,Good,PM2.5,46-013-0004,1,2020-01-19,1579392000,1579392000
19,"Aberdeen, SD",10100,2020-01-20,35,Good,PM2.5,46-013-0004,1,2020-01-20,1579478400,1579478400
20,"Aberdeen, SD",10100,2020-01-21,42,Good,PM2.5,46-013-0004,1,2020-01-21,1579564800,1579564800
21,"Aberdeen, SD",10100,2020-01-22,57,Moderate,PM2.5,46-013-0004,1,2020-01-22,1579651200,1579651200
22,"Aberdeen, SD",10100,2020-01-23,52,Moderate,PM2.5,46-013-0004,1,2020-01-23,1579737600,1579737600
23,"Aberdeen, SD",10100,2020-01-24,26,Good,PM2.5,46-013-0004,1,2020-01-24,1579824000,1579824000
24,"Aberdeen, SD",10100,2020-01-25,25,Good,PM2.5,46-013-0004,1,2020-01-25,1579910400,1579910400
25,"Aberdeen, SD",10100,2020-01-26,33,Good,PM2.5,46-013-0004,1,2020-01-26,1579996800,1579996800
26,"Aberdeen, SD",10100,2020-01-27,27,Good,PM2.5,46-013-0004,1,2020-01-27,1580083200,1580083200
27,"Aberdeen, SD",10100,2020-01-28,30,Good,PM2.5,46-013-0004,1,2020-01-28,1580169600,1580169600
28,"Aberdeen, SD",10100,2020-01-29,39,Good,PM2.5,46-013-0004,1,2020-01-29,1580256000,1580256000
29,"Aberdeen, SD",10100,2020-01-30,45,Good,PM2.5,46-013-0004,1,2020-01-30,1580342400,1580342400
...,...,...,...,...,...,...,...,...,...,...,...
113462,"Yuma, AZ",49740,2020-09-01,31,Good,Ozone,04-027-8011,1,2020-09-01,1598918400,1598918400
113463,"Yuma, AZ",49740,2020-09-02,21,Good,Ozone,04-027-8011,1,2020-09-02,1599004800,1599004800
113464,"Yuma, AZ",49740,2020-09-03,42,Good,PM10,04-027-8011,1,2020-09-03,1599091200,1599091200
113465,"Yuma, AZ",49740,2020-09-04,67,Moderate,Ozone,04-027-8011,1,2020-09-04,1599177600,1599177600
113466,"Yuma, AZ",49740,2020-09-05,60,Moderate,PM10,04-027-8011,1,2020-09-05,1599264000,1599264000
113467,"Yuma, AZ",49740,2020-09-06,46,Good,Ozone,04-027-8011,1,2020-09-06,1599350400,1599350400
113468,"Yuma, AZ",49740,2020-09-07,49,Good,PM2.5,04-027-8011,1,2020-09-07,1599436800,1599436800
113469,"Yuma, AZ",49740,2020-09-08,99,Moderate,PM10,04-027-8011,1,2020-09-08,1599523200,1599523200
113470,"Yuma, AZ",49740,2020-09-09,71,Moderate,PM10,04-027-8011,1,2020-09-09,1599609600,1599609600
113471,"Yuma, AZ",49740,2020-09-10,42,Good,Ozone,04-027-8011,1,2020-09-10,1599696000,1599696000
113472,"Yuma, AZ",49740,2020-09-11,62,Moderate,PM2.5,04-027-8011,1,2020-09-11,1599782400,1599782400
113473,"Yuma, AZ",49740,2020-09-12,69,Moderate,PM2.5,04-027-8011,1,2020-09-12,1599868800,1599868800
113474,"Yuma, AZ",49740,2020-09-13,61,Moderate,PM2.5,04-027-8011,1,2020-09-13,1599955200,1599955200
113475,"Yuma, AZ",49740,2020-09-14,74,Moderate,Ozone,04-027-8011,1,2020-09-14,1600041600,1600041600
113476,"Yuma, AZ",49740,2020-09-15,77,Moderate,PM2.5,04-027-8011,1,2020-09-15,1600128000,1600128000
113477,"Yuma, AZ",49740,2020-09-16,90,Moderate,Ozone,04-027-8011,1,2020-09-16,1600214400,1600214400
113478,"Yuma, AZ",49740,2020-09-17,74,Moderate,Ozone,04-027-8011,1,2020-09-17,1600300800,1600300800
113479,"Yuma, AZ",49740,2020-09-18,84,Moderate,PM2.5,04-027-8011,1,2020-09-18,1600387200,1600387200
113480,"Yuma, AZ",49740,2020-09-19,53,Moderate,PM2.5,04-027-8011,1,2020-09-19,1600473600,1600473600
113481,"Yuma, AZ",49740,2020-09-20,50,Good,PM2.5,04-027-8011,1,2020-09-20,1600560000,1600560000
113482,"Yuma, AZ",49740,2020-09-21,70,Moderate,PM10,04-027-8011,1,2020-09-21,1600646400,1600646400
113483,"Yuma, AZ",49740,2020-09-22,49,Good,PM10,04-027-8011,1,2020-09-22,1600732800,1600732800
113484,"Yuma, AZ",49740,2020-09-23,54,Moderate,PM2.5,04-027-8011,1,2020-09-23,1600819200,1600819200
113485,"Yuma, AZ",49740,2020-09-24,71,Moderate,PM2.5,04-027-8011,1,2020-09-24,1600905600,1600905600
113486,"Yuma, AZ",49740,2020-09-25,49,Good,PM2.5,04-027-8011,1,2020-09-25,1600992000,1600992000
113487,"Yuma, AZ",49740,2020-09-26,34,Good,Ozone,04-027-8011,1,2020-09-26,1601078400,1601078400
113488,"Yuma, AZ",49740,2020-09-27,36,Good,Ozone,04-027-8011,1,2020-09-27,1601164800,1601164800
113489,"Yuma, AZ",49740,2020-09-28,52,Moderate,PM10,04-027-8011,1,2020-09-28,1601251200,1601251200
113490,"Yuma, AZ",49740,2020-09-29,62,Moderate,PM10,04-027-8011,1,2020-09-29,1601337600,1601337600
113491,"Yuma, AZ",49740,2020-09-30,59,Moderate,PM10,04-027-8011,1,2020-09-30,1601424000,1601424000

### Convert to Epoch

In [79]:
dataset_aqi['Epoch'] = (dataset_aqi['Date_new'] - pd.Timestamp("1970-01-01")) // pd.Timedelta('1s')

### Format and rename

In [80]:
dataset_aqi = dataset_aqi.fillna(0)
dataset_aqi['Epoch'].astype(np.int64)


dataset_aqi['timestamp'] = dataset_aqi['Epoch'].astype(np.int64)

final_out = dataset_aqi[['timestamp', 'AQI']].copy()

final_out = final_out.rename(columns={"AQI":"value"})

### Get output

In [81]:
new_anomals = orion.detect(final_out)
new_anomals

983/983 [==============================] - 1s 1ms/step

Empty DataFrame
Columns: [start, end, severity]
Index: []